blank_issues_enabled: false
contact_links:
  - name: ü§î –í–æ–ø—Ä–æ—Å –ø–æ —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–µ
    url: https://github.com/lymp3n/CELL-EVOLUTION/discussions
    about: –ó–∞–¥–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å –∫–æ–º–∞–Ω–¥–µ —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏
  - name: üé® –í–æ–ø—Ä–æ—Å –ø–æ –¥–∏–∑–∞–π–Ω—É
    url: https://github.com/lymp3n/CELL-EVOLUTION/discussions
    about: –û–±—Å—É–¥–∏—Ç–µ –¥–∏–∑–∞–π–Ω–µ—Ä—Å–∫–∏–µ —Ä–µ—à–µ–Ω–∏—è
  - name: üìã –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
    url: https://github.com/lymp3n/CELL-EVOLUTION/wiki
    about: –ß–∏—Ç–∞–π—Ç–µ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—é –ø—Ä–æ–µ–∫—Ç–∞
